export const FALLBACK_TIME_ZONE = "UTC";

export const COUNTRY_TIME_ZONE: Record<string, string> = {
  AT: "Europe/Vienna",
  AU: "Australia/Sydney",
  BE: "Europe/Brussels",
  BY: "Europe/Minsk",
  CA: "America/Toronto",
  CH: "Europe/Zurich",
  CZ: "Europe/Prague",
  DE: "Europe/Berlin",
  DK: "Europe/Copenhagen",
  EE: "Europe/Tallinn",
  ES: "Europe/Madrid",
  FI: "Europe/Helsinki",
  FR: "Europe/Paris",
  GB: "Europe/London",
  IE: "Europe/Dublin",
  IT: "Europe/Rome",
  KZ: "Asia/Almaty",
  LT: "Europe/Vilnius",
  LU: "Europe/Luxembourg",
  LV: "Europe/Riga",
  NL: "Europe/Amsterdam",
  NO: "Europe/Oslo",
  NZ: "Pacific/Auckland",
  PL: "Europe/Warsaw",
  PT: "Europe/Lisbon",
  RU: "Europe/Moscow",
  SE: "Europe/Stockholm",
  UA: "Europe/Kyiv",
  US: "America/New_York",
};
